# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10restaurant.proto\"3\n\x11RestaurantRequest\x12\x0f\n\x07orderID\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\"\x94\x01\n\x12RestaurantResponse\x12\x0f\n\x07orderID\x18\x01 \x01(\t\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.RestaurantResponse.Status\x12\x1b\n\x0bitemMessage\x18\x03 \x03(\x0b\x32\x06.items\"$\n\x06Status\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\"\x19\n\x05items\x12\x10\n\x08itemName\x18\x01 \x01(\t2\xf0\x01\n\nRestaurant\x12\x36\n\tFoodOrder\x12\x12.RestaurantRequest\x1a\x13.RestaurantResponse\"\x00\x12\x37\n\nDrinkOrder\x12\x12.RestaurantRequest\x1a\x13.RestaurantResponse\"\x00\x12\x39\n\x0c\x44\x65ssertOrder\x12\x12.RestaurantRequest\x1a\x13.RestaurantResponse\"\x00\x12\x36\n\tMealOrder\x12\x12.RestaurantRequest\x1a\x13.RestaurantResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'restaurant_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RESTAURANTREQUEST._serialized_start = 20
    _RESTAURANTREQUEST._serialized_end = 71
    _RESTAURANTRESPONSE._serialized_start = 74
    _RESTAURANTRESPONSE._serialized_end = 222
    _RESTAURANTRESPONSE_STATUS._serialized_start = 186
    _RESTAURANTRESPONSE_STATUS._serialized_end = 222
    _ITEMS._serialized_start = 224
    _ITEMS._serialized_end = 249
    _RESTAURANT._serialized_start = 252
    _RESTAURANT._serialized_end = 492
# @@protoc_insertion_point(module_scope)
